### ISSUE TITLE
deep clone implementation causes issues when observing objects with special json serialization behavior

### ISSUE THREAD

**Issue by EricBourland** [Starcounter-Jack/JSON-Patch#144]
if you observe an angular $resource object, generating a patch from it will always have two extra patch operations for the $promise and $resolved properties, because the deep clone implementation removes those two properties. This is because angular $resource objects do not include $promise or $resolved when they JSON.stringify

**Comment by alshakero** [comment]
Have you tried observing a deep cloned copy of your object from the begining to achieve consistency?
As in:
```
observer = jsonpatch.observe( deepClone($resource) );
```
You can collect the `deepClone` function from our code and use it.

For the mean time this works because JSON-Patch compares the data itself disregarding the address of the object, so passing the object or passing a copy of it wouldn't make a difference.

**Comment by EricBourland** [comment]
That does work, but unfortunately in my case I cannot clone the object before passing it in, as I need to observe the original object, not a copy.

**Comment by EricBourland** [comment]
I suggest checking if observer.object has a toJSON function and comparing against the result of calling that in generate instead of comparing against observer.object directly.

**Comment by alshakero** [comment]
Closing as done.
