### ISSUE TITLE
Plans to deprecate -duplex and promote Proxy

### ISSUE THREAD

**Issue by tomalec** [Starcounter-Jack/JSON-Patch#151]
As a continuation to https://github.com/Starcounter-Jack/JSON-Patch/issues/96 with ready and promissing implementation at https://github.com/Starcounter-Jack/JSON-Patch/pull/138

We have draft a brief plan for the future of `json-patch-duplex` and new shiny Proxy version.
Here  what we discussed with @warpech and @alshakero :

1. Create a new repo for JSONPatchProxy/JSONProxyPatch in [PuppetJS](https://github.com/PuppetJs/) organization (to be renamed to Palindrom) as this is quite standalone thing which can do it's job good regardless of `jsonpatch.apply` implementation.
 It will most probably use `fast-json-patch` as dependency but any build, testing, (npm) packaging process would become independent in those two.
2. In this repo, we will mark `json-patch-duplex` as deprecated/obsolated and suggest adopting to new JSONProxyPatch.
3. We will modularize (npm+browserify+ES modules) the code, but keeping in mind fast implementation and development is our goal, not the super flexible and full coverage over all package managers.
3. We will separate useful parts of `-duplex` like `compare`, etc. to be separate module/export but from this repo.
4. Our use cases (Puppet/Palindrom) will switch to Proxy version, so will consume both `fast-json-patch` and `jsonproxypatch` as dependencies.

**Comment by alshakero** [comment]
@tomalec. Gold! Thank you for noting everything. By the end of this week most of this will be done.

**Comment by alshakero** [comment]
So if we agree with JSONProxyPatch, should I call the _class_ JSONProxyPatch? As in `new JSONProxyPatch()`?

**Comment by warpech** [comment]
> So if we agree with JSONProxyPatch, should I call the _class_ JSONProxyPatch? As in `new JSONProxyPatch()`?

This looks correct according to how most official APIs are named in ECMAScript (https://www.ecma-international.org/ecma-262/5.1/#sec-15.12)

**Comment by alshakero** [comment]
So here is the [semi-final version.](https://github.com/alshakero/JSONPatcherProxy) Don't worry about the naming, or the logo (2 mins, not mine).

What I did:

1) Cleaned the code a little bit.
2) Migrated proxy tests. Now they run on Browser and Node.
3) Tested on Edge, Chrome, Safari, IE and FF. Only IE fails.
4) Tested on Safari iOS, Chrome iOS, both work, but tests (not the lib) need perfecting.
5) Packed for NPM.
6) Tested with:
    - CommonJS includes `var a = require('b')`
    - With TS import `import JSONPatcherProxy from 'jsonpatcherproxy'`;
    - With ES6 import `import JSONPatcherProxy from 'jsonpatcherproxy'`;

Next steps:
1) Fixing the six failing specs. And only because of Lodash's array isEqual. 100% not our fault.
2) Maybe renaming, I hope not though.
3) Pushing to the right repo.

**Comment by warpech** [comment]
> Pushing to the right repo.

No need for that, you can just transfer the ownership to the right org.

**Comment by alshakero** [comment]
Update:

- All tests now pass on Edge, Firefox, Chrome and Opera. And on mobile they pass on Safari iOS and Chrome iOS. 
- TS types are legit now, with documentation and IntelliSense works great.

I think this is done so far. I'll move to rename PuppetJS.

**Comment by alshakero** [comment]
Transfered to Palindrom org.

**Comment by alshakero** [comment]
@tomalec should we start deprecating and promoting proxies? And will Palindrom 3.0.0 use them?

**Comment by warpech** [comment]
Update: Patch generation using ES6 Proxy was implemented as a separate package: https://github.com/Palindrom/JSONPatcherProxy

In this repo we have a dirty-checking based patch generation, but it will be deprecated in future.

**Comment by felixfbecker** [comment]
> - We will modularize (npm+browserify+ES modules) the code, but keeping in mind fast implementation and development is our goal, not the super flexible and full coverage over all package managers.
> - We will separate useful parts of -duplex like compare, etc. to be separate module/export but from this repo.

yes please. The code duplication between the duplex and normal version is horrible for making changes.

**Comment by alshakero** [comment]
I'll close this as irrelevant. It doesn't sound like a great idea to kill IE support while it's costing us nothing sitting here. It looks to me those two libs won't be merged anytime soon. 

Unless we decide to invest in version 3.0 with a different API (that allows for internal proxies) because this one doesn't.
