### ISSUE TITLE
Release 3.1.1 request based on PR merged of #262

### ISSUE THREAD

**Issue by adaniels-parabol** [Starcounter-Jack/JSON-Patch#290]
@Starcounter-Jack @alromh87 Could you release for https://github.com/Starcounter-Jack/JSON-Patch as https://github.com/Starcounter-Jack/JSON-Patch/pull/262 was merged in on Aug 13, 2021 which was two commits after 3.1.0 was released. Could you release 3.1.1

**Comment by alromh87** [comment]
Hello @adaniels-parabol im afraid im not the right person to make a Release on JSON-Patch since I created the patch as external contributor, you can clone master and then run `npm run-script build` then you wild find the js on bin directory.

I mergen v3.1.0 with the patch @ https://github.com/alromh87/JSON-Patch/tree/v3.1.0FixPrototypePollution in case you want that

**Comment by Starcounter-Jack** [comment]
Done. Sorry for the delay.
