### ISSUE TITLE
The link to the performance benchmark is broken.

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter-Jack/JSON-Patch#79]
Anyone got a copy?

**Comment by warpech** [comment]
Will add a new one

**Comment by warpech** [comment]
Made new tests:

##### [`add` benchmark](http://jsperf.com/json-patch-benchmark)

<img width="931" alt="screenshot 2015-10-19 16 11 18" src="https://cloud.githubusercontent.com/assets/566463/10580253/f2b87118-767c-11e5-92ab-019abaa4afdb.png">

##### [`replace` benchmark](http://jsperf.com/json-patch-benchmark-replace)

<img width="931" alt="screenshot 2015-10-19 16 16 40" src="https://cloud.githubusercontent.com/assets/566463/10580251/ee033bda-767c-11e5-895c-7a64e15f0abc.png">

Notes:

- Chrome 42 is actually Microsoft Edge (jsperf.com detects it incorrectly)
- I did not manage to test [jiff](https://github.com/cujojs/jiff) and [JSON8](https://github.com/JSON8/patch) because I didn't have time to make a browser build on my own. If anyone can contribute, that would be welcome

Will add to README.md

**Comment by warpech** [comment]
Added to README.md

**Comment by warpech** [comment]
Updated tests thanks to https://github.com/Starcounter-Jack/JSON-Patch/issues/81:

##### [`add` benchmark](http://jsperf.com/json-patch-benchmark/2)

<img width="907" alt="screenshot 2015-10-22 20 35 22" src="https://cloud.githubusercontent.com/assets/566463/10674707/b3deec60-78fc-11e5-876d-59c90a0cab2f.png">

##### [`replace` benchmark](http://jsperf.com/json-patch-benchmark-replace/2)

<img width="904" alt="screenshot 2015-10-22 20 35 58" src="https://cloud.githubusercontent.com/assets/566463/10674708/b6f80d14-78fc-11e5-82c6-658510f31f63.png">

Test ran on 22.10.2015. Compared libraries: 

- [Starcounter-Jack/JSON-Patch](https://github.com/Starcounter-Jack/JSON-Patch) 0.5.4
- [bruth/jsonpatch-js](https://github.com/bruth/jsonpatch-js) 0.5.0 
- [dharmafly/jsonpatch.js](https://github.com/dharmafly/jsonpatch.js) master branch 
- [jiff](https://www.npmjs.com/package/jiff) 0.7.2 browserified
- [json8-patch](https://www.npmjs.com/package/json8-patch) 0.3.2 browserified
