### ISSUE TITLE
Observe callback only in a minute

### ISSUE THREAD

**Issue by bencefrenyo** [Starcounter-Jack/JSON-Patch#88]
Hi,

Object.observe() is not used any more, which is incorrectly stated in Features list. And due to this the previously working instant notification about any change in the object is gone. Not sure that checking changes in regular intervals is efficient. Any plans to improve on this one?

Cheers

**Comment by tomalec** [comment]
Thanks for reporting it :)
@miyconst could you remove O.o from the readme, and comments if any?
@warpech WDYT? Do you have any ideas on how to mimic previous behavior better?Plus, we could expose some API to configure and flush those intervals

**Comment by miyconst** [comment]
Sure, I can do that.

**Comment by warpech** [comment]
In future, we can switch to be using ES6 Proxy.

Right now I guess we should stick with dirty checking. I talked today with @Starcounter-Jack and indeed we think that it might be a good idea to remove time intervals at all. 

@tomalec, @miyconst since we use `dom-bind-notifier`, would we have a way to trigger a `generate` from it without time intervals? We can use some custom DOM event to trigger `generate` if it helps.

**Comment by warpech** [comment]
Long term plan: ES6 Proxy (https://github.com/Starcounter-Jack/JSON-Patch/issues/96)
Short term plan: Remove slowCheck (dirty checking in fixed time intervals) (https://github.com/Starcounter-Jack/JSON-Patch/issues/103)
